#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals, absolute_import, division
__docformat__ = "restructuredtext en"

import unittest

from lxml import html
import textwrap

from nti.contenttools.renders.LaTeX import register
from nti.contenttools.epub.adapters.note import OpenstaxNote
from nti.contenttools.epub.adapters.note import OpenstaxExampleNote

register()

class TestNote(unittest.TestCase):
	
	def test_openstax_note(self):
		html_script = u'<div id="m42092-fs-id3166459" class="note">\
		<div class="title">\
		<span class="cnx-gentext-tip-t">Models, Theories, and Laws</span>\
		</div>\
		<div class="body">\
		<p><span id="m42092-import-auto-id2590130"></span>Models, theories, and laws\
		are used to help scientists analyze the data they have already collected.\
		However, often after a model, theory, or law has been developed, it points\
		scientists toward new discoveries they would not otherwise have made.</p>\
		</div>\
		</div>'
		render_check = u'\n\\begin{sidebar}{Models, Theories, and Laws}\label{m42092-fs-id3166459}\nModels, theories, and laws are used to help scientists analyze the data they have already collected. However, often after a model, theory, or law has been developed, it points scientists toward new discoveries they would not otherwise have made.\n\\end{sidebar}\\newline\n'

		element = html.fromstring(html_script)
		el = OpenstaxNote.process(element, None)
		result = el.render()
		self.assertEqual(result, render_check)

	def test_openstax_example_note(self) :
		self.maxDiff = None
		html_script = u'<div id="m46909-fs-idm64455456" class="example" title="Example&nbsp;1.4.&nbsp;">\
          <div class="title">\
            <span><span class=\
            "cnx-gentext-example cnx-gentext-autogenerated">Example&nbsp;</span><span class="cnx-gentext-example cnx-gentext-n">1.4</span><span class="cnx-gentext-example cnx-gentext-autogenerated">.&nbsp;</span></span>\
          </div>\
          <div class="body">\
            <div xmlns:ncx="http://www.daisy.org/z3986/2005/ncx/" id=\
            "m46909-fs-idm55175232" class="exercise">\
              <!--calling formal.object-->\
              <div class="title">\
                <span><a class="solution-number" href=\
                "#m46909-fs-idm36890624"><span class=\
                "cnx-gentext-exercise cnx-gentext-autogenerated">Problem</span>\
                </a></span>\
              </div>\
              <div class="body">\
                <!--calling informal.object-->\
                <div class="problem">\
                  <span id="m46909-fs-idm56962416"></span>\
                  <p><span id="m46909-fs-idm74506992"></span>Determine what the key terms\
                  refer to in the following study.</p>\
                  <p><span id="m46909-fs-idm35536880"></span>An insurance company would\
                  like to determine the proportion of all medical doctors who have been\
                  involved in one or more malpractice lawsuits. The company selects 500\
                  doctors at random from a professional directory and determines the\
                  number in the sample who have been involved in a malpractice\
                  lawsuit.</p>\
                </div>\
                <div id="m46909-fs-idm36890624" class="solution">\
                  <!--calling formal.object-->\
                  <div class="title">\
                    <span><span class="epub-only pre-text">(</span><a class="solution"\
                    href="ch01.html#m46909-fs-idm55175232">Return to\
                    Problem</a><span class="epub-only post-text">)</span></span>\
                  </div>\
                  <div class="body">\
                    <p><span id="m46909-fs-idm43486032"></span>The <span class=\
                    "bold"><strong>population</strong></span> is all medical doctors\
                    listed in the professional directory.</p>\
                    <p><span id="m46909-fs-idp3077328"></span>The <span class=\
                    "bold"><strong>parameter</strong></span> is the proportion of medical\
                    doctors who have been involved in one or more malpractice suits in\
                    the population.</p>\
                    <p><span id="m46909-fs-idm45173104"></span>The <span class=\
                    "bold"><strong>sample</strong></span> is the 500 doctors selected at\
                    random from the professional directory.</p>\
                    <p><span id="m46909-fs-idp4875616"></span>The <span class=\
                    "bold"><strong>statistic</strong></span> is the proportion of medical\
                    doctors who have been involved in one or more malpractice suits in\
                    the sample.</p>\
                    <p><span id="m46909-fs-idm52360480"></span>The <span class=\
                    "bold"><strong>variable</strong></span> <span class=\
                    "emphasis"><em>X</em></span> = the number of medical doctors who have\
                    been involved in one or more malpractice suits.</p>\
                    <p><span id="m46909-fs-idm41698096"></span>The <span class=\
                    "bold"><strong>data</strong></span> are either: yes, was involved in\
                    one or more malpractice lawsuits, or no, was not.</p>\
                  </div>\
                </div>\
              </div>\
            </div>\
          </div>\
        </div>'
		render_check = u'\n\\begin{sidebar}{Example 1.4. }\label{m46909-fs-idm64455456}\n\\newline \\label{m46909-fs-idm55175232} \\href{#m46909-fs-idm36890624}{Problem                 }\n\nDetermine what the key terms refer to in the following study.\n\\newline An insurance company would like to determine the proportion of all medical doctors who have been involved in one or more malpractice lawsuits. The company selects 500 doctors at random from a professional directory and determines the number in the sample who have been involved in a malpractice lawsuit.\n\\newline \n\\label{m46909-fs-idm36890624} \\\\\\textbf{( \href{ch01.html#m46909-fs-idm55175232}{Return to Problem} )                                     } \\newline\nThe \\textbf{population } is all medical doctors listed in the professional directory.                    \n\nThe \\textbf{parameter } is the proportion of medical doctors who have been involved in one or more malpractice suits in the population.                    \n\nThe \\textbf{sample } is the 500 doctors selected at random from the professional directory.                    \n\nThe \\textbf{statistic } is the proportion of medical doctors who have been involved in one or more malpractice suits in the sample.                    \n\nThe \\textbf{variable } \\textit{X } = the number of medical doctors who have been involved in one or more malpractice suits.                    \n\nThe \\textbf{data } are either: yes, was involved in one or more malpractice lawsuits, or no, was not.\n\\newline\n\\end{sidebar}\\newline\n'
		element = html.fromstring(html_script)
		epub = None
		el =OpenstaxExampleNote.process(element, epub)
		result = el.render()
		self.assertEqual(result, render_check)






